# Server
server.port=8080

# Application name
spring.application.name=backend

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_dictionary
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS cho Vite
app.cors.allowed-origin=*
# API Gemini
gemini.api-key=AIzaSyDhhHfGcdtg9SYXt6gZnMT2gFIPEq71tBs
#AIzaSyDMCGWd0DAFddUFDk59ONdei5IIUQBJ_1A
#AQ.Ab8RN6KQ-C2M7vilcjSluvmNqN-I-yH0qdWtvcHfx09AE2dYJA
#AIzaSyDhhHfGcdtg9SYXt6gZnMT2gFIPEq71tBs
gemini.model=gemini-3.5-flash
gemini.base-url=https://generativelanguage.googleapis.com/v1beta